language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

services:
  - postgresql


before_script:
  - psql -c 'create database andelaap;' -U postgres
  - cp database.yml.travis database.yml


# command to run tests
script:
  - pytest

after_success: coveralls