language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

services:
  - postgresql


before_script:
  - psql -c "CREATE DATABASE andelaapp;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '@Alex.ngari03';" -U postgres


# command to run tests
script:
  - coverage run tests.py -v

after_success: coveralls